{% set name = "lemon" %}
{% set version = "1.3.1" %}
# {% set sha256 = "71b7c725f4c0b4a8ccb92eb87b208701586cf7a96156ebd821ca3ed855bad3c8" %}
{% set sha256 = "e3d7a204a6fdbde8fe87dbc1aa3fd0ae58f908e9fbe8db8a6618db7cd44cdce6" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # url: http://lemon.cs.elte.hu/pub/sources/lemon-{{ version }}.tar.gz
  url: https://github.com/k-dominik/lemon/archive/{{ version }}.tar.gz 
  sha256: {{ sha256 }}
  patches:
   # Note: switching to the conda compilers introduced a build error with
   # clang 4.0.2:
   #   lemon/path.h:231:24: error: no viable conversion from
   #  'typename PredMapPath<Digraph, NodeMap<Arc> >::RevArcIt' to 'value_type'
   # this patch is similar to the proposition in
   # https://stackoverflow.com/a/33641030
   # and uses the explicit cast operator to Arc.
    - 0001-fix-build-error-with-clang-4.patch
   # NOTE: this disables the installation of the glpk dlls
   # from the lemon build system. An issue has been raised upstream
   # for this:
   # http://lemon.cs.elte.hu/pipermail/lemon-devel/2017-May/000392.html
    - 0002-glpk_win.diff
   # The generated LEMONConfig.cmake file hard-codes static
   # library paths, even if BUILD_SHARED_LIBS=1
   # This patch fixes that.
    - 0003-LEMONConfig.cmake.patch
   # export symbols for shared lib on windows
    - 0004-allow-symbols-to-be-exported-in-shard-libs-on-win.patch  # [win]

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('lemon', max_pin='x.x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - glpk
    - coincbc       # [unix]
    - doxygen
    - graphviz
    - ghostscript   # [unix]
  run:
    - glpk
    - coincbc       # [unix]

test:
  commands:
    - test -f $PREFIX/include/lemon/glpk.h                 # [unix]
    - test -f $PREFIX/lib/libemon.so                       # [linux]
    - test -f $PREFIX/lib/libemon.dylib                    # [osx]
    - if not exist %LIBRARY_INC%\\lemon\\glpk.h exit 1     # [win]
    - if not exist %LIBRARY_LIB%\\lemon.lib exit 1         # [win]
    - if not exist %LIBRARY_BIN%\\lemon.dll exit 1         # [win]


about:
  home: https://lemon.cs.elte.hu/trac/lemon
  license: BSL-1.0
  license_file: LICENSE
  summary: 'Library for Efficient Modeling and Optimization in Networks'

extra:
  recipe-maintainers:
    - bluescarni
    - stuarteberg
    - k-dominik
